seL4/website

- templates/sel4-edit.psp
- templates/sel4template.psp
> point to seL4 trademark guidelines 

- .github/workflows/main.yml
> Use more reliable method to comment on PRs

- content/Foundation/Membership/home.pml
> UNSW is now premium

- .github/workflows/main.yml
Signed-off-by: Luke Mondy <luke.mondy@data61.csiro.au>
> Fix caps issue

- content/css/sel4.css
(fixing the dropdown menu colour)
> css: use precise path from bootstrap to override colour

- content/css/sel4.css
Looks nicer and makes it uniform with the other highlights we just introduced.
> pick dark green as the general highlight colour

- content/css/sel4.css
The main effect of this change is that "Served by .." also appears centered.
> css: center footer by default

- content/Foundation/About/home.pml
Signed-off-by: June Andronick <june.andronick@data61.csiro.au>
> adding services in the list on the about page

- content/Foundation/Services/home.pml
Also, use same formatting as for services endorsements.
> Add UNSW logo to AOS endorsement.

- content/images/seL4.svg.license
- content/images/sel4-foundation-logo.svg.license
Some of these were attributed incorrectly.
> license: fix license for logo files

- content/home.pml
- content/news.pml
> Add Penten news item

- content/Foundation/Join/home.pml
> adding info on fees and benefits

- content/home.pml
- content/news.pml
> adding news Item for interim endorsement

- content/Foundation/Services/hc.pml
- content/Foundation/Services/home.pml
> adding HC as services provider

- content/home.pml
- content/news.pml
> adding HC endorsement in the news

- content/home.pml
- content/news.pml
> Add Raytheon news item

- bamboo/Makefile
- bamboo/README.md
- bamboo/assets/bamboo.css
- bamboo/assets/index.html
- bamboo/summary.py
- bamboo/test/.gitignore
- bamboo/test/keys.properties
- bamboo/test/names.properties
- bamboo/test/output-good.html
- bamboo/test/plan.success.txt
- bamboo/test/sha.properties
- content/Use/home.pml
This PR adds a script that bamboo uses to publish log file summaries such as <https://sel4.systems/~bamboo/logs/RELEASE-RUMRPUN-BUILDGHSTATUS/1033/>
The GitHub action for static assets mentioned in the README is coming up in a separate PR.
> Bamboo integration

- .github/workflows/bamboo-pr.yml
- .github/workflows/bamboo.yml
- bamboo/assets/bamboo.css
- bamboo/assets/index.html
This is on top of PR #66 and adds the GitHub action. Probably easiest reviewed when #66 is merged.
> GH deployment + test actions for bamboo script

- bamboo/Makefile
- bamboo/summary.py
- bamboo/test/broken.properties
- bamboo/test/names2.properties
- bamboo/test/output2-good.html
In some scenarios Bamboo might deliver corrupted, partial, empty, or
missing property files. These changes guard against that scenario to
not fail the build in these cases and still produce some output that
might be usable.
Signed-off-by: Gerwin Klein <kleing@unsw.edu.au>
> summary.py: make more robust against garbage input

- content/Foundation/Board/home.pml
> Update Board committees

- content/Foundation/Services/endorsement.pml
- content/Foundation/Services/home.pml
> Remove certification

- content/Foundation/Membership/LOGOS/ETH-Zurich.svg
- content/Foundation/Membership/home.pml
> Add ETH logo

- content/Foundation/Support/home.pml
> Add crowdfunding to Support

- content/Foundation/.names
- content/Foundation/.order
- content/Foundation/About/home.pml
- content/Foundation/Jobs/home.pml
- content/home.pml
- content/news.pml
> adding a page for seL4-related jobs

- content/home.pml
- content/news.pml
> adding the support message as news item

- content/About/home.pml
- content/About/more-research.pml
- content/Foundation/Support/home.pml
- content/Info/.menu
- content/Info/home.pml
> adding a page about seL4 and TS research

- content/home.pml
- content/news.pml
> Kry10 news item

- content/Foundation/Board/home.pml
- content/home.pml
- content/news.pml
> add CEO news item & Board update

- content/home.pml
- content/news.pml
Address https://github.com/seL4/website/issues/94
> Announce new seL4 release

- content/Foundation/Board/home.pml
Looks like there was a copy/paste accident in https://github.com/seL4/website/commit/d6e8eb1dfa569a1fc26b5705b566d8ef141e6ed8
> remove copy/paste accident

- content/About/home.pml
- content/About/more-research.pml
- content/Foundation/About/home.pml
- content/Foundation/Support/home.pml
- content/Info/FAQ/proof.pml
- content/Info/home.pml
- content/Use/home.pml
- content/contact/home.pml
- content/home.pml
- content/news.pml
> De-CSIRO-ise

- content/Foundation/Jobs/home.pml
> adding job ad from DornerWorks

- content/news.pml
> Make Jump news more like others

- content/home.pml
- content/news.pml
> Add new Board news item

- content/Foundation/Membership/home.pml
> Add KSU logo to members page

- content/Foundation/Trademark/home.pml
> fixed link to LF TM guidelines, as per their request

- content/contact/home.pml
> Add social media links

- content/news.pml
> Add forgotten URL in Lotus news

- content/Foundation/Services/home.pml
> add UNSW services endorsement

- content/home.pml
- content/news.pml
> Ghost donation announcement

- content/home.pml
- content/news/2021.pml
> Add news item for latest blog

- content/Foundation/Trademark/home.pml
> LF requested change on TM guidelines

- content/news/2021.pml
> Fix date on latest news item

- content/Foundation/Join/home.pml
> Fix feed rates as per Participation Agreement

- content/news/2021.pml
> Add an anchor for xref

- content/home.pml
- content/news/2021.pml
> news about infoflow on risk-v

- content/news/2021.pml
> Add anchors to news items

- content/news/2021.pml
> Simplify news item anchors

- content/Foundation/Services/home.pml
- fix alt attribute 
- use quotes for tag attribute
> minor fixes

- content/contact/home.pml
> update hangout times

- content/images/sel4-summit-logo.svg
- content/images/sel4-summit-logo.svg.license
- templates/sel4template.psp
> add summit logo to summit page

- content/contact/home.pml
- content/images/sel4-summit-logo.svg
> update dev hangout list

- content/images/sel4-summit-logo.svg
> updated seL4 summit logo to ensure font works across multiple browsers

- content/contact/home.pml
> update developer hangout dates and times

- templates/sel4template.psp
> fix html5 errors

- content/contact/home.pml
> update dates and times for sel4 developer hangouts

- content/Foundation/Jobs/home.pml
- content/Foundation/Summit/cfp.pml
- content/Foundation/Summit/home.pml
- content/Foundation/home.pml
- content/home.pml
- content/news/2020.pml
- content/news/2022.pml
> adding a cfp for the summit

- content/contact/home.pml
> update hangout dates and times

- content/css/sel4.css
- templates/sel4template.psp
> correct footer spacing for mobiles

- content/About/Performance/home.pml
- content/Foundation/Trademark/home.pml
> update TM info; seL4 TM is registered in US

- content/Foundation/Trademark/home.pml
- content/home.pml
- content/news/2022.pml
> add sel4 tm as news item

- .reuse/dep5
- content/home.pml
- content/news/2022.pml
- content/news/seL4-summit-last-call.mp4.license
- content/news/sel4-summit-last-call.mp4.license
> add last call for proposals summit video

- docker/linkchecker.sh
> remove https://lixiang.com from link check

- content/contact/home.pml
> update hangout dates + times

- content/Foundation/Summit/home.pml
> fix types on summit page

- content/contact/home.pml
> update hangouts info

- content/Foundation/Summit/program.pml
Signed-off-by: Gernot Heiser <gernotheiser@users.noreply.github.com>
> Rm (for now) doubtful talk

- content/Foundation/Summit/program.pml
> update typo and auxon talk + presenter

- content/Foundation/Summit/home.pml
- content/Foundation/Summit/principles.pml
- content/Foundation/Summit/program.pml
> add info re summit mentorship/rego

- content/Foundation/Summit/home.pml
- content/Foundation/Summit/program.pml
> add minor updates to summit program

- content/Foundation/Summit/home.pml
- content/Foundation/Summit/program.pml
- content/home.pml
- content/news/2022.pml
> add registration info

- content/Foundation/Summit/home.pml
> update summit info

- content/home.pml
> add summit tab to seL4 home page

- content/Foundation/Summit/home.pml
- content/Foundation/Summit/program.pml
> change minor errors

- content/Foundation/Summit/abstracts/seL4CP-bootcamp.pml
- content/Foundation/Summit/abstracts2022.pml
- content/Foundation/Summit/home.pml
- content/Foundation/Summit/program.pml
- content/css/sel4.css
- content/home.pml
> add summit news item and minor updates

- content/Foundation/Membership/home.pml
- content/home.pml
- content/news/2022.pml
> announce SpacemiT joining

- content/news/2022.pml
> fix id in news items

- content/Foundation/Summit/home.pml
- content/Foundation/TSC/home.pml
- content/css/sel4.css
- content/home.pml
- content/news/2021.pml
- content/news/2022.pml
> add sponsor to summit page

- content/Foundation/Membership/home.pml
- content/Foundation/Summit/home.pml
- content/Foundation/Summit/program.pml
- content/news/2022.pml
> change in program - exp reports

- content/Foundation/Summit/home.pml
- content/Foundation/Summit/program.pml
- content/css/sel4.css
- content/home.pml
- content/news/2022.pml
> add session chairs; add Xcalibyte sponsor

- content/news/2022.pml
> horizon requestes wording tweak

- content/home.pml
- content/news/2022.pml
> add kataos news item

- content/Foundation/Board/Minutes/home.pml
> add board meeting minutes

- content/news/2022.pml
> add link to news item

- content/css/sel4.css
Required for https://github.com/seL4/ci-actions/pull/271
> Add monospace class for table data cell

- content/Foundation/Summit/2023/home.pml
- content/css/sel4.css
- content/home.pml
- content/news/2023.pml
@june-andronick Draft done, but sponsor grids need centering. Will do next week.
> draft of gold sponsor announcement

- content/Foundation/Membership/home.pml
> remove member logo

- content/Foundation/Summit/abstracts2022.pml
- content/Foundation/Summit/cfp.pml
- content/Foundation/Summit/home.pml
- content/Foundation/Summit/program.pml
- templates/sel4-edit.psp
- templates/sel4template.psp
Change copyright year in footer to 2024
Fix copyright year on summit pages where incorrect
> fix copyright years

- content/Contribute/home.pml
> change isabelle link to https

- content/Foundation/Summit/2024/cfp.pml
- content/Foundation/Summit/2024/home.pml
- content/Foundation/Summit/2024/submit.pml
- content/home.pml
- content/news/2024.pml
> add draft of cfp and submission portal

- content/Foundation/Membership/home.pml
- content/css/sel4.css
> remove member; update css

- README.md
Describe requirement for relative links and how to produce them.
This doesn't have a description of what relative links/paths actually are. Not sure if that is needed or can be assumed.
> README: describe relative link requirement

- README.md
- fix typos
- link to homebrew
> README: improve rbenv install instructions

- Foundation/TSC/index.html
- Makefile
- contact/index.html
- point to new process
- remove mentions of old Jira
- update links to individual RFCs
> point website at GitHub RFC process implementation

- index.html
- news/2024.html
Announcing the seL4 13.0.0 release
> seL4 release news item

- Foundation/Jobs/index.html
- Foundation/Membership/index.html
- Foundation/Summit/2022/index.html
- _news-items/2021-08-25-trentos.html
The 3-col grid on the membership page did not have the Cyberagentur logo. (The single column mobile grid did show it.)
> add member to 3-col grid

- _on_seL4.yml
> seL4 config: remove beta site URL

- .github/workflows/site-deploy.yml
Since ${{ secrets.WEB_HOST_KEYS }} is just some verbatim text with newlines, use a here-document instead to write the contents to a file.
> github: use `<<` instead of `<<<`

- tools.html
Just a couple things I noticed regarding TS projects while looking at the new site.
> Minor fixes/clarifications to tools page

- roadmap.html
To be merged after the new docs site is live.
> Fix roadmap link for Microkit

- Summit/2025/index.html
summit sponsorship opportunities closed for 2025
> remove summit sponsor button
