.github/workflows/main.yml
As per: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
this should allow PRs from forks to still deploy test websites.
It means that PRs of the infrastructure itself won't get tested as part of the PR though.
=> To allow PRs from forks, use pull_request_target

.github/workflows/main.yml
This reverts commit 92006f2b46a6d82269672b9911c77d4c90ff2f07.
This is not what we wanted - it does not run the actions on the code
from the PR itself, meaning its previews (for example) are not useful
We still have the issue of GitHub secrets not being shared with forks, which prevents the deploy step :thinking: 
I think the intermediate solution is that PRs should be branches for now, until we work something out.
=> Revert "To allow PRs from forks, use pull_request_target"

docker/Makefile, docker/apache-up.sh, docker/run-local.sh, docker/snapshot.sh
This PR provides scripts and a `Makefile` target to serve the website locally in a docker container.
This should make previewing much quicker.
=> run website locally

content/css/sel4.css
This colour is the same hue as neutral/neutralLight, but sits between them
in saturation and lightness. Should have better contrast with the rest of
the text, but still be readable on white.
Should hopefully fix issue #31.
=> css: new link colour

.github/workflows/main.yml
See also
https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w
and
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
=> github workflows: remove deprecated set-env

content/.ignore
certbot creates a directory .well-known and puts stuff in it.
git should ignore that (ephemeral) stuff, and indeed, the entire directory.
Adding the directory to .ignore means it won't ever be committed by mistake.
Signed-off-by: Peter Chubb <Peter.Chubb@data61.csiro.au>
=> Ignore .well-known directory so certbot can work

docker/linkchecker.sh
The site returns 404 if queried by `wget` without user agent, but
works fine otherwise. Instead of trying to do something smart, we
assume that ETH will be around longer than the seL4 website.
=> ignore ETH link

.github/workflows/main.yml
I initially thought the culprit was the different handling of newlines in `env` described here:
<https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable>
But it turns out it's the javascript action further below in the script, which just wanted `\n` quoted in its input string.
=> multiline message handling changes

content/Foundation/Services/home.pml
There was a typo that would show up on google search results.
=> Fixed the Typo for the AOS Course Code

code/ertos.py
-- use importlib.machinery not imp
-- Remove unused imports
-- fix pyflakes errors
-- Remove dead code (py_handler, get_news_elements)
-- Use io.open not open() so we get the correct charset encoding.
Signed-off-by: Peter Chubb <peter.chubb@unsw.edu.au>
=> Fixes for Python 3.9

content/home.pml, content/news/2020.pml, content/news/2021.pml, content/news/home.pml
As we get more and more news, having it all in one
file becomes unwieldy.  Plus, we would like to be able to have
stable URLs to news and news items.
Therefore, split news into per-year files, named 'news/2021.pml',
'news/2020.pml' and so on; and use the Python templating engine
to build indices, and to redirect from 'sel4.systems/news' to the
highest numbered news file.
Signed-off-by: Peter Chubb <peter.chubb@unsw.edu.au>
=> Move News to a subdirectory; split by year.

docker/linkchecker.sh
The link checker seems to have intermittent issues with https://nio.com. Since we know this link is good, exclude it from the check.
=> docker: exclude flaky link in checker

docker/Makefile, docker/build.sh
Since the purpose of the container mostly is to check changes locally, we currently just run the build in x86 emulation mode for M1.
Getting a native M1 build running would need an apache python module on arm64 for python 3.7 and Debian buster, or an overall working Debian bullseye setup.
=> docker: enable docker build on Apple M1

docker/linkchecker.sh
Looks like the site doesn't like link checkers.
=> linkchecker: ignore rtx.com

content/contact/home.pml
- adds a Google calendar feed for foundation events and dates, incl hangouts
- update hangout dates. We might reduce these to just the next date in the future now that the calendar exists.
=> add calendar feed

content/contact/home.pml
This looks reasonable enough. The styling clashes slightly with the seL4 theme, but not too badly in the agenda view.
If this works correctly, times should show in the local time zone of the client.
=> display inline calendar for seL4 hangouts+events

content/Info/FAQ/proof.pml
The RISC-V proofs now have the same strength of assumptions as ARM.
(also adjust research link to go to main TS page instead of the old TS project)
=> update FAQ with RISC-V proofs

code/ertos.py, templates/sel4template.psp
Website is now owned and authored by the seL4 Foundation, not Data61.  Reflect this in the template and default title.
=> Fix author and title

.github/workflows/main.yml
Update to current node16 versions. The old node12 actions are deprecated and will stop working.
=> github: bump GitHub action versions

.github/workflows/site-deploy.yml
Automatically buuild deploy site to GitHub Pages by pushing the generated content to the gh-pages branch.
=> github: deploy site to GitHub Pages

.github/workflows/main.yml
Only comment when linkchecker or validator failed, but do not show link to preview.
=> github: disable preview for PRs for now

.github/workflows/main.yml
- job outputs are strings, so need to be compared to strings.
- make message construction more robust, so that we at least get an empty message, not an error, if the above still fails.
- bump `github/script` action version to Node 20 to avoid warnings
=> fix PR commenter error

Foundation/Summit/2023/abstracts2023.html, Foundation/Summit/2023/program.html
Fix YouTube URLs for summit 2023 videos, which were reloaded to YouTube to add sponsor logos.
=> Fix youtube links summit 2023

_includes/crumb.html, _includes/menu.html, _layouts/default.html, _layouts/news.html
Relative in jekyll terminology only means relative to the root of the site, not relative to the current page, but the root can be set via base_url.
This is a first step towards making previews work again and should not have any effect on the generated html yet. The only difference should be that if you now set `base_url`, the links generated from templates (menu, breadcrumbs, css, etc) will point to the right location.
=> make template URLs relative

About/index.html, Contribute/index.html, Foundation/Jobs/index.html, Foundation/Services/cog.html, Foundation/Services/dornerworks.html, Foundation/Services/hc.html, Foundation/Services/index.html, Foundation/Summit/2023/index.html, Foundation/Trademark/logo.html, Foundation/index.html, Info/index.html, Use/index.html, index.html, news/2020.html, news/2021.html, news/2022.html, news/2023.html, news/2024.html
This makes all manual links (a href and img src) on the site use relative paths, which should enable previews with varying path prefixes in the next step.
=> make all links document-relative

.github/workflows/main.yml, _preview.yml
This changes the previous preview setup and no longer uses the htmlpreview repo. Instead our own `website_pr_hosting` repo now has GitHub pages enabled and the PR preview is deployed to there in a subdirectory (one per PR).
=> github: deploy preview to website_pr_hosting repo

.github/workflows/pr-cleanup.yml
Avoid filling up the root directory in the `gh_pages` branch with hundreds of PR previews. When the PR is closed, the preview should no longer be needed.
The PRs will still accumulate in the repo history, but CI only ever pulls with depth 1, and we should never need to manually clone the repo.
=> github: remove preview when PR is closed

_news-items/2024-07-02-release.md
This was one of the early files and it looks like some of the line breaks got scrambled in the html-to-md conversion.
(I haven't seen that kind of effect on the other converted news items)
=> news: fix html conversion accident

_includes/footer_icons.html, _includes/footer_text.html, _layouts/default.html
This footer was previously only enabled on the desktop version of the site.
=> Add served-by-seL4 footer to mobile pages

About/index.html, Learn/index.html, Makefile, _news-items/2021-08-13-defcon.html
- TS has moved HACMS page
- DARPA has moved HACMS page
- GettingStarted was renamed to Resources on docsite
- exclude collinsaerospace.com from link check, because it thinks a link check is DOS
=> fix broken links

.linkcheck-ignore.yml
The Makefile should eventually draw its list of ignored URLs from here.
We currently ignore all .html files and all files in `_` directories, because the separate website link check takes care of these. This leaves mostly the README.md file for now.
This will work with https://github.com/seL4/ci-actions/pull/390
=> set up .ignore file for link checker

.github/workflows/site-deploy.yml
Build the `on_seL4` version of the website in addition to the vanilla version. Make both available as download artifacts.
~~Does not yet deploy to anywhere else than the `gh_pages` branch.~~
Now contains deployment to the seL4 server and backup server as a separate commit.
=> github: build on_seL4 version

.github/workflows/site-deploy.yml
Use `<<<` to write the known hosts variable into the file. The `echo` method doesn't deal well with newlines.
=> github: avoid echo for writing known_hosts

Gemfile.lock
Installing the gems on current darwin-24 (sequoia) will modify the Gemfile.lock file to include the architecture, even though no other content changes.
=> Gemfile.lock: add current darwin version

_data/platforms.json, platforms.html, tools.html
In my opinion, once the docs site is revamped then this page should just link to there (or have this site somehow read from the same source of truth as the docs site to avoid mismatches between info here and on the supported platforms page).
=> Various minor fixes

_data/benchmarks.json, _includes/bench-comp-table.html, _includes/benchmark-table.html, performance.html
sel4bench will be providing the performance results as json data, which we can then render here.
This eliminates the need for the data extraction python script to understand how the website works.
=> generate performance page in jekyll

Contribute/git-conventions.md, _includes/green-roadmap-li.html, _news-items/9999-12-31-template.md
- remove typo/unclear side sentence in git-conventions
- fix dark mode title for roadmap items
- news template: document new parameters
=> Small website fixes

Makefile
Getting 429 and 403 respectively, because they are all defending against crawlers. External link checking is becoming increasingly useless.
=> Makefile: ignore linkedin and stackecxchange links
